### ISSUE TITLE
Wrong Language setup confirmation message

### ISSUE THREAD

**Issue by impeeza** [HamletDuFromage/nx-locale-switcher#2]
Hi, I have a Unpatched Erista Switch.
CFW: Atmosphère 1.2.6
Bootloader: Hekate 5.7.0
I load HBL as a title
I am using NC-Locale-Switcher 1.1.1

After setting the language for a title the confirmation dialog doesn't shows the correct code of the language just set, only shows ({}) except for the default system which display "Default System Language (en-US)" for me.

I am attaching screenshots, that happens on every title I have installed
![2022020509451700-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646968-c0f753dc-48cb-4ed9-a5e1-bad614593681.jpg)
![2022020509452000-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646970-bfbddde7-df5f-4a58-a07d-e18651b4ae5d.jpg)
![2022020509452200-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646971-4d3c37a3-ef70-486e-a60b-40a357c9bf30.jpg)
![2022020509452600-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646973-5a306e56-dc33-434b-b0ff-59fd01d3c88e.jpg)
![2022020509452900-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646974-24310983-5355-4c34-8c07-9ff0fb2704f5.jpg)
![2022020509453000-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646975-cbb1655e-9f38-4631-93c0-c3294049dc10.jpg)
![2022020509453300-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646976-7ec9675a-8649-4d87-b627-502c13a47013.jpg)
![2022020509453600-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646977-c96dbafe-25ac-46f4-ab0b-fe731c65cc78.jpg)
![2022020509454000-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646978-58c97adf-3851-4799-9666-48eab94cf3c4.jpg)
![2022020509454200-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646979-8d53e6c2-f6f3-4d55-8d54-4aa9a3d01877.jpg)
![2022020509454500-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646980-0da9e6b3-5976-4197-85a8-a46ea5618b90.jpg)
![2022020509454800-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646982-920e79d6-3304-45b1-b966-c93c420ce095.jpg)
![2022020509455000-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646984-a490d7e7-1625-453f-b830-23c447138f7b.jpg)
![2022020509455200-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646986-344de7b4-5bbc-4761-9186-f7c873be59ab.jpg)
![2022020509455500-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646987-8e1abc60-71aa-4c88-9c2c-bf98219f3d3e.jpg)
![2022020509455900-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646989-41a2ada9-b9b0-4560-8c0b-394ead11afcf.jpg)
![2022020509460200-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646990-f10de1f4-d4c5-438b-8349-76fb1586b4c7.jpg)
![2022020509460600-16851BE00BC6068871FE49D98876D6C5](https://user-images.githubusercontent.com/41979604/152646991-ebd1bff8-e396-4e17-85fb-c44f1c048aee.jpg)

Thanks a lot for your effort and good work.

**Comment by HamletDuFromage** [comment]
Fixed in 1.1.2 https://github.com/HamletDuFromage/nx-locale-switcher/releases/tag/1.1.2
Thanks :)
